### ISSUE TITLE
TE-C_55X_Autopilot is not displayed

### ISSUE THREAD

**Issue by ryma52** [QuackDerBruchpilot/STE-C_55X_Autopilot#4]
Hi
With great pleasure I came across your plugin "STE-C 55X Autopilot" and installed it immediately in XP11. The plugin is displayed in the XP menu. But I can neither call the setup nor the plugin itself. 

![2022-11-20 06_10_21-X-System](https://user-images.githubusercontent.com/83553506/202886992-a735e298-654d-4990-9a50-9dabb1773709.jpg)

Any idea how this can be fixed. Looking forward to occasional replies.

Best Regards, Marcel

PS: 
Bin Schweizer, kannst mir auch deutsch antworten. Hier noch die Log.txt, die gefühlte Tausende Fehlermeldungen betr. dieses Plugins beinhaltet.
[Log.zip](https://github.com/QuackDerBruchpilot/STE-C_55X_Autopilot/files/10048947/Log.zip)

**Comment by QuackDerBruchpilot** [comment]
Hi Marcel,

for a better understanding for non german-speakers we'll stay in english here. I hope you agree with me.

I investigated the problem and found out that the plugin was unable to load two .png files from the resources.
Can you go to _plugins - STE-C 55X AP -> data -> modules -> Custom Module -> images_ and check if there are two files 'icons8-checked-checkbox-20' and 'icons8-unchecked-checkbox-20' present?

Viele Grüße aus der **Sächsischen**-Schweiz ;)
Luka

**Comment by ryma52** [comment]
Hi Luka

Yes, that is so. The two files are available. Here is a screenshot:

![TE-C_55X_AP](https://user-images.githubusercontent.com/83553506/202902775-f3e87bfa-3332-4a1b-bc1d-d49278e4a427.jpg)

Best regards, Marcel

**Comment by QuackDerBruchpilot** [comment]
That's strange.

But I can not reproduce the issue at all.
Maybe try to remove all the other plugins and then add them one by one and try if it loads now.

I could imagine that SASL interferres with another plugin I don't have.

**Comment by ryma52** [comment]
Still the same. Have previously removed all additional six installed plugins and restarted XP11. Doesn't matter to me at this time. I'll leave it alone. 
I experimented with XP12 for over a month and severely disappointed went back to XP11 where everything works great (except this plugin). I'm not experimenting anymore. I want to fly. I hope for your understanding.

Best regards, Marcel

**Comment by QuackDerBruchpilot** [comment]
That's very sad but I understand that.

Happy Landings :)
